Cambiar Logo Kobotoolbox por uno de Scanterra
scanterra/enketo-express pull request #4
Opened 2020-09-22 14:30 UTC by LaimeJesus

Armar un Pull Request bien detallado ayuda a que sea facil de entender para todos.

## Tarea de Origen

Link: #1 

## Descripcion

Se actualizó el branding de enketo, se cambió el Logo de Kobotoolbox por uno de Scanterra

## New Features

- Se puede ver el Logo de Scanterra al momento de crear un nuevo registro

2020-09-23 11:08 UTC, asassano requested changes
Se aplicaron los codeowners, template y permisos de ramas.
Lo que creo que sería prolijo es dejar "develop/1.70.1" limpia sin ningún commit adicional, osea original de como se creo del commit correspondiente y aplicar todos los PR y commit propios sobre "develop_st". Si les parecen apliquen los PR corrigiendo esto. Gracias

ver: https://github.com/scanterra/enketo-express/issues/3#issuecomment-697293459

2020-09-23 18:17 UTC, LaimeJesus commented
> Se aplicaron los codeowners, template y permisos de ramas.
> Lo que creo que sería prolijo es dejar "develop/1.70.1" limpia sin ningún commit adicional, osea original de como se creo del commit correspondiente y aplicar todos los PR y commit propios sobre "develop_st". Si les parecen apliquen los PR corrigiendo esto. Gracias
> 
> ver: [#3 (comment)](https://github.com/scanterra/enketo-express/issues/3#issuecomment-697293459)

Me parece que no es necesario, ya tenemos en el historial de PRs los commits que implementamos en cada rama, y de dónde salen estos.

2020-09-25 14:25 UTC, asassano approved these changes, later dismissed
@cristiandley cuando puedas revisalo así ya @LaimeJesus hace el merge

2020-10-06 17:59 UTC, cristiandley requested changes

2020-10-06 17:59 UTC, cristiandley commented on app/views/surveys/component/_form-header.pug
> +  if (logo.source)
No hay necesidad de dos condiciones, podria estar en una sola.

2020-10-06 18:18 UTC, LaimeJesus commented on app/views/surveys/component/_form-header.pug
> +  if (logo.source)
Te referís a esto?

```pug
  if (logo.source)
    if (logo.href)
      a.form-header__branding(href=`${logo.href || '#'}`)
    else
      .form-header__branding
    .logo-wrapper
        img(src=`${logo.source}`, alt="brand logo")
```
Los dos `ifs` son necesarios porque si no está definido `logo.source` no hay nada para mostrar.

2020-10-06 20:47 UTC, cristiandley commented on app/views/surveys/component/_form-header.pug
> +  if (logo.source)
Consulta, y por que `href={a || b}` si ya hicieron falsy `logo.href` en el if de linea 8  ? no convendria tener un default del elemento ?

2020-10-06 20:56 UTC, LaimeJesus commented on app/views/surveys/component/_form-header.pug
> +  if (logo.source)
@cristiandley 
1) Eso si es raro.
2) Ya hay un `logo.source` y `logo.href` por defecto usado en la aplicación, solo que este componente no está implementado para considerar diferentes casos.  
No me parece necesario implementar esa lógica porque no vamos a cambiar el objeto que se crea al iniciar la aplicación. Ver [Documentación](https://github.com/scanterra/enketo-express/blob/develop_st/config/README.md#logo)

Voy a implementar el cambio 1) con la otra mejora que mostré.

2020-10-06 21:38 UTC, LaimeJesus commented on app/views/surveys/component/_form-header.pug
> +  if (logo.source)
@cristiandley 
Actualizados los cambios en este [commit](https://github.com/scanterra/enketo-express/pull/4/commits/7ef45942d7fedff4c8502113d96e9775f90cec4d)

2020-10-07 00:08 UTC, cristiandley approved these changes

2020-10-07 16:36 UTC, asassano approved these changes
@LaimeJesus mergea cuando puedas

2020-10-07 17:36 UTC, merged